In [2]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt  
import seaborn as sns

In [5]:
customers=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_customers_dataset.csv")

In [6]:
geolocation=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_geolocation_dataset.csv")

In [7]:
order_items=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_order_items_dataset.csv")

In [8]:
payments=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_order_payments_dataset.csv")

In [9]:
reviews=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_order_reviews_dataset.csv")

In [3]:
orders=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_orders_dataset.csv")

In [11]:
products=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_products_dataset.csv")

In [12]:
sellers=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\olist_sellers_dataset.csv")

In [16]:
category_translation=pd.read_csv(r"H:\python\Projects\Olist_Data_Analytics\data\raw\product_category_name_translation.csv")

# 1. Dataset Overview

The Olist Brazilian E-Commerce dataset contains multiple related
tables covering customers, orders, products, sellers, payments,
reviews and geographical information.

The objective of this project is to perform an end-to-end
data analysis using Python.

In [17]:
print("Customers:", customers.shape)
print("Geolocation:", geolocation.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Geolocation: (1000163, 5)
Order Items: (112650, 7)
Payments: (103886, 5)
Reviews: (99224, 7)
Orders: (99441, 8)
Products: (32951, 9)
Sellers: (3095, 4)
Category Translation: (71, 2)

In [18]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [19]:
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [21]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [24]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [27]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [28]:
orders.isna()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
99436,False,False,False,False,False,False,False,False
99437,False,False,False,False,False,False,False,False
99438,False,False,False,False,False,False,False,False
99439,False,False,False,False,False,False,False,False
99440,False,False,False,False,False,False,False,False

In [30]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [31]:
orders.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Length: 99441, dtype: bool

In [32]:
orders.duplicated().sum()

np.int64(0)

In [35]:
missing_value_percentage= orders.isna().sum()/orders.shape[0]*100

In [36]:
missing_value_percentage

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [37]:
orders["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [39]:
orders["order_status"].nunique()

8

In [40]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [41]:
orders["order_status"].value_counts().sum()

np.int64(99441)

value_counts(normalize=True) give us proportion.A proportion means (part/Total)

In [44]:
orders["order_status"].value_counts(normalize=True)

order_status
delivered      0.970203
shipped        0.011132
canceled       0.006285
unavailable    0.006124
invoiced       0.003158
processing     0.003027
created        0.000050
approved       0.000020
Name: proportion, dtype: float64

In [46]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [57]:
orders["order_purchase_timestamp"]=pd.to_datetime(orders["order_purchase_timestamp"])

In [ ]:
orders["order_purchase_timestamp"].dtype

dtype('<M8[ns]')

In [62]:
orders["order_purchase_timestamp"].dt.year

0        2017
1        2018
2        2018
3        2017
4        2018
         ...
99436    2017
99437    2018
99438    2017
99439    2018
99440    2018
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [63]:
orders["order_purchase_timestamp"].dt.month

0        10
1         7
2         8
3        11
4         2
         ..
99436     3
99437     2
99438     8
99439     1
99440     3
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [79]:
orders["order_purchase_timestamp"].dt.day

0         2
1        24
2         8
3        18
4        13
         ..
99436     9
99437     6
99438    27
99439     8
99440     8
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [65]:
orders["order_purchase_timestamp"].dt.day_name()

0           Monday
1          Tuesday
2        Wednesday
3         Saturday
4          Tuesday
           ...
99436     Thursday
99437      Tuesday
99438       Sunday
99439       Monday
99440     Thursday
Name: order_purchase_timestamp, Length: 99441, dtype: object

In [68]:
orders["order_delivered_customer_date"]=pd.to_datetime(orders["order_delivered_customer_date"])

In [100]:
orders["order_approved_at"]=pd.to_datetime(orders["order_approved_at"])

In [101]:
orders["order_delivered_carrier_date"]=pd.to_datetime(orders["order_delivered_carrier_date"])

In [103]:
orders["order_estimated_delivery_date"]=pd.to_datetime(orders["order_estimated_delivery_date"])

In [70]:
orders["order_delivered_customer_date"].dtype

dtype('<M8[ns]')

In [81]:
(orders["order_delivered_customer_date"]-orders["order_purchase_timestamp"]).dt.days

0         8.0
1        13.0
2         9.0
3        13.0
4         2.0
         ...
99436     8.0
99437    22.0
99438    24.0
99439    17.0
99440     7.0
Length: 99441, dtype: float64

In [82]:
orders["delivery_days"]=(orders["order_delivered_customer_date"]-orders["order_purchase_timestamp"]).dt.days

In [ ]:
orders["delivery_days"]

0         8.0
1        13.0
2         9.0
3        13.0
4         2.0
         ...
99436     8.0
99437    22.0
99438    24.0
99439    17.0
99440     7.0
Name: delivery_days, Length: 99441, dtype: float64

In [87]:
orders["delivery_days"].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

### Quantile

`quantile()` tells us the value at a specific position in the sorted data.

- `quantile(0)` → Minimum value (0th percentile)
- `quantile(0.25)` → 25th percentile (Q1)
- `quantile(0.50)` → 50th percentile = **Median**
- `quantile(0.75)` → 75th percentile (Q3)
- `quantile(1)` → Maximum value (100th percentile)

For example, if we use `delivery_days`:

- `0` → shortest delivery time
- `0.50` → median delivery time
- `1` → longest delivery time

**Important:** The number inside `quantile()` represents the position/percentile of the data, from 0 to 1.

In [98]:
orders["delivery_days"].quantile()

np.float64(10.0)

In [104]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_days                    2965
dtype: int64

In [106]:
orders["order_approved_at"].isna().sum()

np.int64(160)

In [107]:
orders["order_delivered_carrier_date"].isna().sum()

np.int64(1783)

In [108]:
orders["order_delivered_customer_date"].isna().sum()

np.int64(2965)

In [118]:
orders["order_delivered_customer_date"].isna().value_counts()

order_delivered_customer_date
False    96476
True      2965
Name: count, dtype: int64

In [ ]:
orders[
orders["order_delivered_customer_date"].isna()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [4]:
orders[(orders["order_status"]=="delivered") & (orders["order_delivered_customer_date"].isna())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00